/*!
Windows Hello, as the difference between a keypress and a person.

The approval card in [`crate::ai::approval`] proves that a key was pressed. It
does not prove who pressed it, and on Windows a keypress is the cheapest thing
in the world to manufacture: `SendInput` is one call, Sill itself declares
[`crate::action::Capability::InputInjection`] because it makes them, and so
does every other program running as the same account. A card that a model can
be talked into answering on its own behalf is a card that protects nothing.

Windows Hello is the one answer in the box that no software path can
synthesise. A face, a fingerprint or a Hello PIN is checked by the credential
broker in another process, and the only thing that satisfies it is somebody
being at the machine.

## What this module is, and is not

The edge, and only the edge. Whether a given action needs a person is decided
by [`crate::ai::acting::gate`], which is a pure function over the capabilities
and this module's [`Availability`], so every case is testable without a
fingerprint reader. Everything here talks to Windows, and the only part of it
that can be tested on a machine with no Hello is the [`Availability`] mapping.

## Why the interop and not the plain call

`UserConsentVerifier::RequestVerificationAsync` is the WinRT method, and it
does not work in a desktop process: it has no window to be modal against and
fails rather than prompting. Microsoft's answer for Win32 is
`IUserConsentVerifierInterop`, which takes an `HWND`, and it is the only
version of this that works in Sill. That interface is not generated by the
`windows` crate, so it is declared below, which is the whole of the unsafe
code here.
*/

use serde::{Deserialize, Serialize};

/// How long a Hello prompt waits before it counts as unanswered.
///
/// The same ninety seconds the approval card waits, deliberately: the two are
/// answers to the same question asked in two ways, and a person who walks away
/// from one has walked away from the other. Refusing on silence is the only
/// safe direction, which is [`crate::ai::approval`]'s rule as well.
pub const PATIENCE: std::time::Duration = std::time::Duration::from_secs(90);

/// What this machine can prove about who is at it.
///
/// Windows reports five states and they are kept apart rather than folded into
/// a boolean, because the difference between them is the sentence somebody
/// reads when the gate turns out to be weaker than they expected. "Not set up
/// on this PC" is something they can fix in Settings; "turned off by a policy"
/// is not, and telling them the wrong one wastes their afternoon.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Availability {
    /// A face, a fingerprint or a Hello PIN can be asked for.
    Ready,
    /// Nothing on this machine can check a person.
    NoDevice,
    /// The machine can, but this account has enrolled nothing.
    NotSetUp,
    /// A policy on this machine forbids it.
    Blocked,
    /// The reader is in the middle of something else.
    Busy,
    /// Windows could not be asked, or answered with something new.
    Unknown,
}

impl Availability {
    pub fn ready(self) -> bool {
        matches!(self, Self::Ready)
    }

    /// Why a person cannot be asked, in the words a card uses.
    ///
    /// `None` when they can, because there is nothing to explain. Every other
    /// arm has a sentence of its own for the same reason
    /// [`crate::ai::acting::what_it_touches`] does: the line somebody reads is
    /// the only part of this they ever see, and a shared default that says
    /// "unavailable" about a policy and about a missing reader tells them
    /// nothing they can act on.
    pub fn why(self) -> Option<&'static str> {
        Some(match self {
            Self::Ready => return None,
            Self::NoDevice => "Windows Hello is not set up on this PC",
            Self::NotSetUp => "Windows Hello is not set up for your account",
            Self::Blocked => "Windows Hello is turned off by a policy on this PC",
            Self::Busy => "the Windows Hello reader is busy",
            Self::Unknown => "Windows could not say whether Windows Hello is available",
        })
    }
}

/// How a prompt was answered.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Verdict {
    /// A person was there, and Windows recognised them.
    Verified,
    /// They said no, or ran out of tries.
    Refused,
    /// Nobody answered inside [`PATIENCE`].
    Unanswered,
    /// Windows would not ask. **Not a yes**, and treated as a refusal by the
    /// caller: availability already said this machine could do it, so a
    /// failure here is Hello declining rather than Hello being absent.
    Trouble(String),
}

#[cfg(windows)]
mod edge {
    // The interface's method names are Windows' own, which is the point: they
    // have to line up with something somebody else defined.
    #![allow(non_snake_case)]

    use super::{Availability, Verdict};

    use windows::Security::Credentials::UI::{
        UserConsentVerificationResult, UserConsentVerifier, UserConsentVerifierAvailability,
    };
    use windows::Win32::Foundation::HWND;
    use windows_core::{Interface, HSTRING};
    use windows_future::IAsyncOperation;

    /**
    The Win32 half of `UserConsentVerifier`, which the `windows` crate does not
    generate.

    One real method, and the `HWND` is the entire reason the interface exists:
    the WinRT method beside it assumes a window the runtime already knows
    about, and a Tauri process has none of those. `39E050C3-...` is the
    interface's published IID and the signature is its published one; both are
    fixed by Windows rather than chosen here.

    **The three slots above it are not padding.** This derives from
    `IInspectable`, whose vtable sits between `IUnknown`'s and the method
    below, and the macro can only build a vtable out of what is declared. They
    are named for what Windows puts there so that anybody counting slots can
    see the layout is right; nothing here calls them.
    */
    #[windows_core::interface("39E050C3-4E74-441A-8DC0-B81104DF949C")]
    unsafe trait IUserConsentVerifierInterop: windows_core::IUnknown {
        unsafe fn GetIids(
            &self,
            count: *mut u32,
            iids: *mut *mut windows_core::GUID,
        ) -> windows_core::HRESULT;
        unsafe fn GetRuntimeClassName(
            &self,
            name: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT;
        unsafe fn GetTrustLevel(&self, level: *mut i32) -> windows_core::HRESULT;
        unsafe fn RequestVerificationForWindowAsync(
            &self,
            window: HWND,
            message: *mut core::ffi::c_void,
            wanted: *const windows_core::GUID,
            operation: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT;
    }

    pub fn available() -> Availability {
        let asked = match UserConsentVerifier::CheckAvailabilityAsync() {
            Ok(asked) => asked,
            Err(err) => {
                crate::log::write(&format!("[hello] could not ask Windows: {err}"));
                return Availability::Unknown;
            }
        };

        match asked.join() {
            Ok(UserConsentVerifierAvailability::Available) => Availability::Ready,
            Ok(UserConsentVerifierAvailability::DeviceNotPresent) => Availability::NoDevice,
            Ok(UserConsentVerifierAvailability::NotConfiguredForUser) => Availability::NotSetUp,
            Ok(UserConsentVerifierAvailability::DisabledByPolicy) => Availability::Blocked,
            Ok(UserConsentVerifierAvailability::DeviceBusy) => Availability::Busy,
            // A state Windows grew after this was written. Unknown rather than
            // Ready: a name nobody here has read is not a promise that a
            // person can be asked for.
            Ok(other) => {
                crate::log::write(&format!("[hello] Windows said {other:?}"));
                Availability::Unknown
            }
            Err(err) => {
                crate::log::write(&format!("[hello] could not ask Windows: {err}"));
                Availability::Unknown
            }
        }
    }

    pub fn verify(window: isize, message: &str, patience: std::time::Duration) -> Verdict {
        let operation = match start(window, message) {
            Ok(operation) => operation,
            Err(err) => return Verdict::Trouble(format!("Windows Hello would not ask: {err}")),
        };

        /*
         * The completion is taken on a channel rather than by `join`, which is
         * the blocking wait the crate offers, because `join` has no patience:
         * a prompt raised over MCP for somebody who is not at their desk would
         * hold that turn open until they came back. Ninety seconds and then
         * `Cancel`, so the dialog goes away rather than sitting on their
         * screen unexplained an hour later.
         */
        let (tell, told) = std::sync::mpsc::channel();
        let handler = windows_future::AsyncOperationCompletedHandler::new(move |_, _| {
            let _ = tell.send(());
            Ok(())
        });

        if let Err(err) = operation.SetCompleted(&handler) {
            return Verdict::Trouble(format!("Windows Hello would not answer: {err}"));
        }

        if told.recv_timeout(patience).is_err() {
            let _ = operation.Cancel();
            return Verdict::Unanswered;
        }

        match operation.GetResults() {
            Ok(UserConsentVerificationResult::Verified) => Verdict::Verified,
            // Both of these are somebody deciding: the cancel is the button,
            // and running out of tries is the reader deciding for them.
            Ok(UserConsentVerificationResult::Canceled)
            | Ok(UserConsentVerificationResult::RetriesExhausted) => Verdict::Refused,
            Ok(other) => Verdict::Trouble(format!("Windows Hello said {other:?}")),
            Err(err) => Verdict::Trouble(format!("Windows Hello would not answer: {err}")),
        }
    }

    /// Puts the prompt up and hands back the operation to wait on.
    fn start(
        window: isize,
        message: &str,
    ) -> windows_core::Result<IAsyncOperation<UserConsentVerificationResult>> {
        let interop = windows_core::factory::<UserConsentVerifier, IUserConsentVerifierInterop>()?;
        let message = HSTRING::from(message);
        let mut operation = std::ptr::null_mut();

        // SAFETY: the message outlives the call, `wanted` names the interface
        // the out pointer is then read as, and `operation` is a null pointer
        // Windows either fills or leaves alone. The raw pointer is adopted
        // once, by the `from_raw` below, so its one reference is owned here.
        unsafe {
            interop
                .RequestVerificationForWindowAsync(
                    HWND(window as *mut core::ffi::c_void),
                    core::mem::transmute_copy(&message),
                    &IAsyncOperation::<UserConsentVerificationResult>::IID,
                    &mut operation,
                )
                .ok()?;

            Ok(IAsyncOperation::from_raw(operation))
        }
    }
}

/// Whether a person can be asked for on this machine.
///
/// Asked every time rather than remembered, and it costs nothing to do so: it
/// runs only when an action is already stopping to ask, which is never while
/// Sill is idle. Remembering it would mean somebody who enrols a fingerprint
/// while Sill is running keeps the weaker gate until they restart, and it
/// would mean a reader unplugged mid-session still counts.
#[cfg(windows)]
pub fn available() -> Availability {
    edge::available()
}

#[cfg(not(windows))]
pub fn available() -> Availability {
    Availability::NoDevice
}

/// Asks the person at the machine to prove it, and waits.
///
/// **Blocking.** `window` is the `HWND` the prompt is modal against. Call it
/// from somewhere a block is fine, which for Sill means
/// `tauri::async_runtime::spawn_blocking`: the launcher's event loop and the
/// tokio worker running the model's turn both have to stay free while a
/// dialog is on screen for up to `patience`.
#[cfg(windows)]
pub fn verify(window: isize, message: &str, patience: std::time::Duration) -> Verdict {
    edge::verify(window, message, patience)
}

#[cfg(not(windows))]
pub fn verify(_window: isize, _message: &str, _patience: std::time::Duration) -> Verdict {
    Verdict::Trouble("Windows Hello needs Windows".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every state that is not `Ready` says why, because that sentence is the
    /// whole of what somebody is told when the gate turns out to be weaker
    /// than the setting promised.
    #[test]
    fn everything_short_of_ready_says_why() {
        for state in [
            Availability::NoDevice,
            Availability::NotSetUp,
            Availability::Blocked,
            Availability::Busy,
            Availability::Unknown,
        ] {
            assert!(!state.ready(), "{state:?} counts as ready");
            assert!(state.why().is_some(), "{state:?} has no words");
        }
    }

    /// And the one that is has nothing to explain.
    #[test]
    fn being_ready_needs_no_explanation() {
        assert!(Availability::Ready.ready());
        assert_eq!(Availability::Ready.why(), None);
    }

    /// The reasons are told apart. Four states sharing one sentence would send
    /// somebody to a Settings page that cannot help them.
    #[test]
    fn each_reason_is_its_own_sentence() {
        let said: Vec<&str> = [
            Availability::NoDevice,
            Availability::NotSetUp,
            Availability::Blocked,
            Availability::Busy,
            Availability::Unknown,
        ]
        .into_iter()
        .filter_map(Availability::why)
        .collect();

        let mut unique = said.clone();
        unique.sort_unstable();
        unique.dedup();

        assert_eq!(unique.len(), said.len(), "two states say the same thing");
    }

    /// The wait is the card's wait. Two different patiences would mean the
    /// same question answered by silence in two different lengths of time.
    #[test]
    fn the_wait_matches_the_card() {
        assert_eq!(PATIENCE, std::time::Duration::from_secs(90));
    }
}
